Check that cppExamples compile, link, and run in unittests workflow.

diff --git a/.github/workflows/unittests.yml b/.github/workflows/unittests.yml
--- a/.github/workflows/unittests.yml
+++ b/.github/workflows/unittests.yml
@@ -161,12 +161,28 @@ jobs:
             Add-Content -Path $env:GITHUB_OUTPUT -Value "statuscode=$statuscode"
             exit $statuscode
 
+      - name: cpp_test
+        id: cpp_test
+        if: matrix.os != 'windows-2022'
+        run: |
+          cd addon/cppExamples
+          mkdir build
+          cd build
+          cmake ..
+          make
+          examples=("flashes" "saturation" "tp_properties" "tv_properties")
+          nfailed=0
+          for exmp in "${examples[@]}"; do echo "Running $exmp"; ./"$exmp" > /dev/null; if [[ $? -ne 0 ]]; then echo "$exmp exited with code $? (failure)."; ((nfailed++)); else echo "$exmp exit 0 (success)"; fi; done
+          echo "statuscode=$nfailed" >> $GITHUB_OUTPUT
+          exit $nfailed
+      
       - name: Check success
         if: matrix.os != 'windows-2022'
         run: |
             echo "Fortran test result : ${{ steps.fortran_test.outputs.statuscode }}"
             echo "Python test result : ${{ steps.python_test.outputs.statuscode }}"
-            if [[ ${{ steps.fortran_test.outputs.statuscode }} -eq 0 ]] && [[ ${{ steps.python_test.outputs.statuscode }} -eq 0 ]]; then
+            echo "C++ test result : " ${{ steps.cpp_test.outputs.statuscode }}
+            if [[ ${{ steps.fortran_test.outputs.statuscode }} -eq 0 ]] && [[ ${{ steps.python_test.outputs.statuscode }} -eq 0 ]] && [[ ${{ steps.cpp_test.outputs.statuscode }} -eq 0 ]]; then
             exit 0
             else
             exit 1
